baseURL = "https://www.ramanaam.com/"
title = "Rama Naam"
author = "Bhakt"
copyright = "NO COPYRIGHT - ∞ - ∞, Feel Free to make the world Happy :)"
paginate = 50
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
description = "hello"
theme = "paper"
enableRobotsTXT = true
disableKinds = ['sitemap','robotsTXT']

[params]
  color = 'white'
  description = 'Rama Naam | Mantra benefits in Kaliyuga, Mantra Counter, Kaliyuga keval naam adhara sumir sumir nahin utrahin para'

# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
